### ISSUE TITLE
Add support for http server

### ISSUE THREAD

**Issue by mklan** [TooTallNate/nx.js#102]
Hey it's me again. Would it be difficult to integrate the following Lib? It would be awesome to be able to spawn a local server.

https://github.com/QuickJS-web-project/quickwebserver

**Comment by TooTallNate** [comment]
Ya, I want to add this. I think it would make more sense to implement it in JavaScript on top of the `Switch.Socket` as an installable package. So something like:

```typescript
import { Server } from '@nx.js/http';

Server.listen({
	port: 8080,
	async fetch(request) {
		return new Response('Hello World!');
	},
);
```

**Comment by mklan** [comment]
Oh yeah that would make sense. Awesome can't wait :)

**Comment by TooTallNate** [comment]
I've added a `@nx.js/http` package that you can install into your app which offers some basic HTTP server functionality. It's pretty basic at the moment, but might solve your needs. Let me know if there's any functionality missing that you need!
