### ISSUE TITLE
[Feature Request] append to file

### ISSUE THREAD

**Issue by mklan** [TooTallNate/nx.js#117]
Hey. I have the problem, that I cannot write large files, because I need to keep the whole blob in memory. Is it possible to implement an fs function to append a buffer to a file? This way I could write in chunks.

Thanks!

**Comment by TooTallNate** [comment]
So do you actually want to _append_ to an existing file (as in, through multiple runs of the app, like appending to a log file for example)? Or are you more interested in a streaming interface for writing a file?

**Comment by mklan** [comment]
Hey! streaming would be more preferable for my usecase. 

Btw of topic: I got the chance to check out the http package and it is awesome! Nice work! When I find time I plan  to contribute some parser for url parameters and a small router. I tried Post requests but it seems to fail. I will try to pinpoint it and will create an issue

**Comment by TooTallNate** [comment]
You can probably have luck with one of the existing packages on npm for URL pattern matching: https://www.npmjs.com/search?q=keywords%3Aurl%20pattern

And ya, please do make an issue if you find a reproduction for any issue with the HTTP package.

**Comment by TooTallNate** [comment]
`Switch.file()` is now published in v0.0.46.
