### ISSUE TITLE
Building tests fails

### ISSUE THREAD

**Issue by mklan** [TooTallNate/nx.js#127]
Hey,

I am facing issues building your tests. 
I get the following error:   `The module "./src/index.js" was not found on the file system.`

I could monkey-patch it by adding the src folder from your uvu fork to `node_modules/uvu`. 
Creating an nro also failed and I had to install and use `nxjs-pack`.

Thanks!

**Comment by TooTallNate** [comment]
Can you outline the steps you are taking to build it? I typically do `./build.sh tests` from the root of the repo, then upload the `apps/tests/tests.nro` file onto the Switch.

**Comment by TooTallNate** [comment]
Note that `nxjs-pack` was renamed to `nxjs-nro`. Thus `nxjs-pack` is deprecated.

**Comment by mklan** [comment]
ah ok thanks for the info. When running the build script I get devkitpro error. I think I removed the toolkit a while ago. I will reopen the issue, when I find some time :)
