### ISSUE TITLE
file api error: not a function

### ISSUE THREAD

**Issue by mklan** [TooTallNate/nx.js#128]
Hey, 

When I try to call `Switch.file(path)` it throws `TypeError: not a function`. The tests are also failing for me. Am I missing maybe something?

**Comment by TooTallNate** [comment]
Can you paste the full stack trace? Are you sure you're using nx.js v0.0.46 or newer?

**Comment by TooTallNate** [comment]
Glad to hear it's working for you now. Create a new issue for the localStorage thing if you're still having issues.
