### ISSUE TITLE
Game doesn't appear.

### ISSUE THREAD

**Issue by RileyDevGithub** [TooTallNate/nx.js#51]
I did the getting started documentation, but the app doesn't appear.

Does the Switch need to be modded?

**Comment by RileyDevGithub** [comment]
Here is my file structure:
microSD:
	Nintendo:
		[nintendo switch data stuff]
	switch:
		nxjs.nro
		nxjs.js

**Comment by TooTallNate** [comment]
Yes, you Switch needs to be modded to run homebrew applications. Once that is set up, then the game would appear in the Album menu homebrew launcher.

**Comment by RileyDevGithub** [comment]
Nooooooooooooooo

**Comment by TooTallNate** [comment]
😅 Ya, sorry, there's no way around that. I've updated the instructions in the README to clarify, so that this issue can be closed.
