### ISSUE TITLE
video m3u8 support?

### ISSUE THREAD

**Issue by PhamMinhKha** [TooTallNate/nx.js#62]
Does nx.js support video streaming. I plan to play videos through nx.js with m3u8 stream file format
Google translator

**Comment by TooTallNate** [comment]
There is not yet and video player functionality. I'd actually prefer to keep that out of the core nx.js, and instead have a suggested npm module that would implement that on top of the Canvas (and eventually Audio) interfaces that nx.js provides.

**Comment by PhamMinhKha** [comment]
It would be great if nx.js supported it. Thank you for your project.

**Comment by TooTallNate** [comment]
What could possibly make sense is to implement the [WebCodecs API](https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API) in nx.js core, so that applications would have native access to i.e. ffmpeg for decoding various media formats.

**Comment by HoangVanThu965** [comment]
Is there any example of playing a video using nx.js? I've been trying to use ffmpeg.js, but encountered a lot of errors
