### ISSUE TITLE
Get game list and launch games

### ISSUE THREAD

**Issue by kirankunigiri** [TooTallNate/nx.js#64]
This project looks awesome! I would love to use it to build a custom game launcher with more features, similar to uLaunch. I know the API's are still in progress, but was wondering if there's already a way to get the list of games on the device and launch them.

**Comment by TooTallNate** [comment]
There is not currently, but I would accept adding that kind of functionality. If you can find an example of C code that does this, then I could look into adding a JS API for that.

**Comment by kirankunigiri** [comment]
Hi, does this help? I found some C code from libnx that I think adds this functionality, although I'm not familiar with C code.

[`appletRequestLaunchApplication`](https://github.com/switchbrew/libnx/blob/master/nx/source/services/applet.c) - Launch applications
[`nsListApplicationRecord`](https://github.com/switchbrew/libnx/blob/master/nx/source/services/ns.c) - Get list of applications

Let me know if this can work for nx.js and be implemented, thanks!

**Comment by TooTallNate** [comment]
Thanks @kirankunigiri, that was helpful. I've added a new iterator API `Switch.applications`, which yields instances of `Switch.Application`, and you can launch an individual application with `app.launch()`.

Check out the [`app-launch`](https://github.com/TooTallNate/nx.js/blob/main/apps/app-launch/src/main.ts) example to see how it works.
