### ISSUE TITLE
fetch 302 Redirect does not work

### ISSUE THREAD

**Issue by mklan** [TooTallNate/nx.js#80]
Hallo, thanks for this awesome project!

When I fetch an url that is being redirected, then nothing happens and it just returns 302. I see the static method redirect in the code base, but is never used. The default option for redirect in fetch seems to be 'follow' tho.

Does someone have any hints? Thanks!

**Comment by mklan** [comment]
For now I can just look if the location response header is set and then refetch

**Comment by TooTallNate** [comment]
Good call. Will get that fixed ASAP.
