### ISSUE TITLE
[Bug] remove and removeSync fails to remove file

### ISSUE THREAD

**Issue by mklan** [TooTallNate/nx.js#82]
Hello, when I try to remove a file it throws an error that the file or directory has not been found. Deleting folders works tho.

**Comment by TooTallNate** [comment]
Thanks for the report. Fixed in the v0.0.30 release.

**Comment by mklan** [comment]
Thanks for the fast iterations!

**Comment by mklan** [comment]
![Uploading 2024012511405700-DB1426D1DFD034027CECDE9C2DD914B8.jpg…]()

**Comment by mklan** [comment]
fixed: https://github.com/TooTallNate/nx.js/issues/85
