### ISSUE TITLE
nxjs-pack is not distributing latest nxjs.nro

### ISSUE THREAD

**Issue by mklan** [TooTallNate/nx.js#85]
`nxjs-pack`is not distributing latest `nxjs.nro`. 
After updating the runtime the remove file fixes were still broken. I found out that `node_modules/nxjs-pack/dist/nxjs.nro` is outdated. After copying the latest release manually everything works as expected!

**Comment by TooTallNate** [comment]
Oh wow, good catch. Fixed by https://github.com/TooTallNate/nx.js/commit/6e502b2f77ad819b19acfdfaa7394e607ce2f913.

**Comment by TooTallNate** [comment]
I verified that the latest published package includes the correct version.
